export const UPDATE_LOADING_TIME = 'UPDATE_LOADING_TIME';
export const UPDATE_HANDLE_OPEN_STATE = 'UPDATE_HANDLE_OPEN_STATE';
export const SET_ROWS = 'SET_ROWS'
export const SET_COLUMNS = 'SET_COLUMNS'
export const SET_DATA = 'SET_DATA'
export const SET_RESPONSE_TIME = 'SET_RESPONSE_TIME'